-- =========================================================================
-- CASE STUDY: Spotify Music Streaming Logs Analysis
-- =========================================================================
-- Purpose: Aggregate song streaming frequencies, play times, and artist metrics.
-- Demonstration: Joins, SUM aggregates, and order sorting logic.
-- =========================================================================

-- 1. DATABASE SCHEMA CREATION (DDL)

CREATE TABLE spotify_tracks (
    track_id INT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    artist VARCHAR(100) NOT NULL,
    duration_sec INT CHECK (duration_sec > 0)
);

CREATE TABLE play_history (
    play_id INT PRIMARY KEY,
    track_id INT,
    plays INT NOT NULL DEFAULT 0,
    FOREIGN KEY (track_id) REFERENCES spotify_tracks(track_id) ON DELETE CASCADE
);


-- 2. POPULATE DUMMY RECORDS (DML)

INSERT INTO spotify_tracks (track_id, title, artist, duration_sec) VALUES 
(1, 'Blinding Lights', 'The Weeknd', 200),
(2, 'Levitating', 'Dua Lipa', 203),
(3, 'Starboy', 'The Weeknd', 230);

INSERT INTO play_history (play_id, track_id, plays) VALUES 
(4001, 1, 15200),
(4002, 2, 9800),
(4003, 3, 12100);


-- 3. ANALYTICAL CASE QUESTIONS & ANSWERS

-- Challenge 1: List all songs along with their play counts, sorted by plays descending.
-- Expected Output: Track titles and their play stats.
SELECT t.title, p.plays 
FROM spotify_tracks t 
JOIN play_history p ON t.track_id = p.track_id
ORDER BY p.plays DESC;

-- Challenge 2: Calculate the total streams generated by the artist 'The Weeknd'.
-- Expected Output: Cumulative play count for all tracks by the artist.
SELECT SUM(p.plays) AS total_plays 
FROM spotify_tracks t 
JOIN play_history p ON t.track_id = p.track_id 
WHERE t.artist = 'The Weeknd';
